# Generated by Django 2.2 on 2020-07-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('inStock', models.IntegerField(blank=True, null=True)),
                ('isSold', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='forums')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currentuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='EcommerceApp.User')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='EcommerceApp.List')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='forums')),
                ('extra', models.IntegerField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='EcommerceApp.Item')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='currentuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='EcommerceApp.User'),
        ),
        migrations.AddField(
            model_name='list',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteminCart', to='EcommerceApp.Item'),
        ),
        migrations.AddField(
            model_name='list',
            name='selected',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='EcommerceApp.Option'),
        ),
    ]
